sudo: required
services: -docker

before_install:
  - docker build -t kpizzle/docker-react -f Dockerfile.dev .

script:
  # '-e ci=true' is env var so that tests exit and travis doesn't hang
  - docker run -e CI=true kpizzle/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: '$AWS_ACCESS_KEY'
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
  region: 'eu-west-2'
  app: 'dockerApp'
  env: 'Dockerapp-env'
  bucket_name: elasticbeanstalk-eu-west-2-380402590287
  on:
    branch: master
