sudo: required
services: -docker

before_install:
  - docker build -t kpizzle/docker-react -f Dockerfile.dev .

script:
  # -e ci=true is env var so that tests exit and travis doesn't hang
  - docker run -e CI=true kpizzle/docker-react npm run test -- --coverage
